### ISSUE TITLE
Project Peer Review

### ISSUE THREAD

**Issue by ngarcia2024** [thealibi/mysite#1]
Overall, I really like how your website is very clean and the way the navigation bar is on the left side. I also use Brave and it is great!

Content Suggestions:
1.  I think you can add some more pictures and content overall on the pages to make it more personal and entertaining. 
2. On my works page maybe you can add some work that you have done in the past or create another page about some things you are working on. 

Technical Suggestions:
1.  Making the content on the screen adjust to different screen sizes. The content can be seen clearly when I am in full-screen mode, but when I change it the content on the screen disappears and I need to move the screen to see it.  
2.  Having the content on the different pages, shown in the same spot would make the website a lot easier to navigate and see. I think adjusting the padding and borders would definitely help with this.

**Comment by thealibi** [comment]
Thank you for the feedback. I will implement these changes.
