### ISSUE TITLE
Peer Review

### ISSUE THREAD

**Issue by ines-pl** [thealibi/mysite#2]
You have a great website so far, here are just some suggestions.

Issue 1: Make your sitemap look like the rest of your pages. Same format.
Issue 2: On the contact page add a margin between your name email and your comments boxes.
Issue 3: You could use target in your href to ensure the user doesn't go off your page, but another tab is just opened on the services you use page.
Issue 4: Make your tables responsive so that when the window is shrunk it doesn't disappear. This could be done by setting the margin-left and margin-right of your table to auto.

**Comment by thealibi** [comment]
Thank you for the feedback. I will implement these changes.
